name: vimix # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Live video mixing # 79 char long summary
title: vimix - Graphical Live Video Mixing
description: |
  vimix performs graphical mixing and blending of multiple videos, 
  with image processing effects in real-time.
  The mix ouput is typically projected full-screen on an external 
  monitor or a projector, and can be recorded live (no audio).
icon: snap/gui/vimix.svg
license: GPL-3.0+
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  vimix:
    command: usr/local/bin/vimix
    #command: desktop-launch $SNAP/usr/bin/vimix
    #desktop: ../snap/gui/vimix.desktop
    plugs:
      - desktop
      - wayland
      - x11
      - opengl
      - removable-media
      - home
    environment:
          GST_PLUGIN_SYSTEM_PATH : $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
          GST_PLUGIN_SCANNER: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0/gst-plugin-scanner

parts:
  vimix-binary:
    plugin: cmake
    source: .
    cmake-parameters: 
    -  -DCMAKE_BUILD_TYPE=RelWithDebInfo
    build-packages:
    -  g++
    -  make
    -  libpng-dev
    -  libxrandr-dev
    -  libglfw3-dev
    -  libgstreamer1.0-dev
    -  libgstreamer-plugins-base1.0-dev
    stage-packages:
    -  libpng16-16
    -  libglu1-mesa
    -  freeglut3
    -  libglfw3
    -  gstreamer1.0-tools
    -  libgstreamer1.0-0
    -  libgstreamer-gl1.0-0
    -  libgstreamer-plugins-base1.0-0
    -  libgstreamer-plugins-good1.0-0
    -  gstreamer1.0-libav
    -  gstreamer1.0-plugins-base
    -  gstreamer1.0-plugins-good
    -  gstreamer1.0-plugins-bad
    -  gstreamer1.0-plugins-ugly
    
 
